# Generated by Django 4.0.6 on 2022-07-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_bid_listing_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('FASHION', 'Fashion'), ('TOYS', 'Toys'), ('ELECTRONICS', 'Electronics'), ('HOME', 'Home'), ('SPORTS', 'Sports')], default=None, max_length=11, null=True),
        ),
    ]
